# -*- coding: utf-8 -*- 
import os 
from flask import Flask, render_template_string, request 
app = Flask(__name__) 
@app.route('/', methods=['GET', 'POST']) 
def home(): 
    res = None 
    if request.method == 'POST': 
        res = "active" 
    h = "<html><head><title>MAIA II - FULL STACK</title><style>" 
    h += "body{background:#050505; color:#0ff; font-family:monospace; padding:20px; margin:0;}" 
    h += ".panel{border:1px solid #0ff; padding:20px; background:#001111; margin-bottom:20px; box-shadow: 0 0 15px rgba(0,255,255,0.1);}" 
    h += ".tree-container{background:#000; border-left: 2px solid #f0f; padding:15px; height:500px; overflow-y:scroll;}" 
    h += "details{margin:8px 0; border-bottom: 1px solid #111;}" 
    h += "summary{cursor:pointer; color:#ffff00; font-weight:bold; padding:5px; outline:none;}" 
    h += "summary:hover{color:#0ff;}" 
    h += ".file{color:#0f0; margin-left:30px; padding:4px; display:block; font-size:0.9em; text-decoration:none;}" 
    h += ".file::before{content: '[-] ';}" 
    h += ".code-window{background:#000; color:#0f0; padding:25px; border:1px solid #333; border-left:5px solid #f0f; min-height:800px; overflow-x:hidden; white-space:pre; line-height:1.6; font-size:0.95em;}" 
    h += "input{width:40%; background:#000; color:#0ff; border:1px solid #0ff; padding:12px; margin-right:10px;}" 
    h += "button{padding:12px 20px; font-weight:bold; cursor:pointer; border:none; text-transform:uppercase; margin:5px;}" 
    h += ".btn-lab{background:#f0f; color:#000;} .btn-main{background:#0ff; color:#000;}" 
    h += ".lab-section{border:1px dashed #f0f; padding:20px; background:rgba(255,0,255,0.02);}" 
    h += "</style></head><body>" 
    h += "<h1>[ M.A.I.A. II - DEFENSE & AEROSPACE MODULE ]</h1>" 
    h += "<div class='panel lab-section'><h2>PROJECT LAB</h2>" 
    h += "<form method='post'><input name='drone_idea' placeholder='Nombre del Proyecto...'>" 
    h += "<button type='button' class='btn-lab'>BUSCADOR DE PROYECTO</button>" 
    h += "<button type='submit' class='btn-lab'>CREAR NUEVO PROYECTO</button></form></div>" 
    h += "<div class='panel'><h2>ARBOL DE DIRECTORIOS (14 NODOS)</h2>" 
    h += "<div class='tree-container'>" 
    h += "<details><summary>01_CORE_RTOS</summary><div class='file'>os_kernel.c</div><div class='file'>tasks_priority.h</div></details>" 
    h += "<details open><summary>02_CONTROL_ATTITUDE</summary><div class='file'>mahony_filter.py</div><div class='file'>pid_controller.cpp</div></details>" 
    h += "<details><summary>03_NAVIGATION_ASTAR</summary><div class='file'>voxel_grid.cpp</div><div class='file'>path_optimizer.py</div></details>" 
    h += "<details><summary>04_PERCEPTION_THERMAL</summary><div class='file'>radiometric_proc.py</div><div class='file'>target_tracking.py</div></details>" 
    h += "<details><summary>05_PERCEPTION_LIDAR</summary><div class='file'>ouster_driver.py</div><div class='file'>point_cloud_filter.cpp</div></details>" 
    h += "<details><summary>06_TELEMETRY_MAVLINK</summary><div class='file'>mavlink_v2_encoder.py</div><div class='file'>status_packets.h</div></details>" 
    h += "<details><summary>07_POWER_BMS</summary><div class='file'>can_bms_driver.cpp</div><div class='file'>energy_management.py</div></details>" 
    h += "<details><summary>08_COMM_SILVUS</summary><div class='file'>mesh_network.py</div><div class='file'>encryption_aes256.c</div></details>" 
    h += "<details><summary>09_DIAGNOSTICS_HEALTH</summary><div class='file'>system_monitor.py</div><div class='file'>failsafe_logic.cpp</div></details>" 
    h += "<details><summary>10_SIMULATION_SITL</summary><div class='file'>gazebo_bridge.py</div><div class='file'>physics_model.py</div></details>" 
    h += "<details><summary>11_MISSION_PLANNER</summary><div class='file'>waypoint_manager.py</div><div class='file'>geofencing.cpp</div></details>" 
    h += "<details><summary>12_HARDWARE_HAL</summary><div class='file'>gpio_map.h</div><div class='file'>i2c_bus_config.c</div></details>" 
    h += "<details><summary>13_AI_INFERENCE</summary><div class='file'>tensorrt_engine.py</div><div class='file'>object_detection.py</div></details>" 
    h += "<details><summary>14_FILESYSTEM_LOGS</summary><div class='file'>blackbox_logger.c</div><div class='file'>data_sync.py</div></details>" 
    h += "</div></div>" 
    h += "<div class='panel'><h2>VISOR DE CODIGO VERTICAL</h2>" 
    h += "<div class='code-window'>" 
    h += "// ARCHIVO: control/mahony_filter.py\\n" 
    h += "// DESCRIPCION: Fusion sensorial avanzada (Filtro Mahony)\\n\\n" 
    h += "import numpy as np\\n\\n" 
    h += "class MahonyIMU:\\n" 
    h += "    def __init__(self, Kp=2.0, Ki=0.005, freq=400):\\n" 
    h += "        self.q = np.array([1.0, 0.0, 0.0, 0.0]) # Cuaternion de actitud\\n" 
    h += "        self.e_int = np.zeros(3) # Error integral\\n" 
    h += "        self.dt = 1.0 / freq\\n\\n" 
    h += "    def update(self, gyro, acc):\\n" 
    h += "        # Normalizacion de acelerometro\\n" 
    h += "        a_norm = np.linalg.norm(acc)\\n" 
    h += "        if a_norm < 0.01: return\\n" 
    h += "        acc /= a_norm\\n\\n" 
    h += "        # Direccion estimada de la gravedad\\n" 
    h += "        v = np.array([\\n" 
    h += "            2*(self.q[1]*self.q[3] - self.q[0]*self.q[2]),\\n" 
    h += "            2*(self.q[0]*self.q[1] + self.q[2]*self.q[3]),\\n" 
    h += "            self.q[0]**2 - self.q[1]**2 - self.q[2]**2 + self.q[3]**2\\n" 
    h += "        ])\\n\\n" 
    h += "        # Error de producto cruzado\\n" 
    h += "        error = np.cross(acc, v)\\n" 
    h += "        self.e_int += error * self.dt\\n\\n" 
    h += "        # Ajuste de velocidad angular\\n" 
    h += "        gyro_corr = gyro + 2.0 * error + 0.005 * self.e_int\\n\\n" 
    h += "        # Integracion de cuaternion\\n" 
    h += "        q_dot = 0.5 * self.q_multiply(self.q, [0, *gyro_corr])\\n" 
    h += "        self.q = self.q + q_dot * self.dt\\n" 
    h += "        self.q /= np.linalg.norm(self.q)\\n\\n" 
    h += "    def q_multiply(self, q, p):\\n" 
    h += "        w1, x1, y1, z1 = q\\n" 
    h += "        w2, x2, y2, z2 = p\\n" 
    h += "        return np.array([\\n" 
    h += "            w1*w2 - x1*x2 - y1*y2 - z1*z2,\\n" 
    h += "            w1*x2 + x1*w2 + y1*z2 - z1*y2,\\n" 
    h += "            w1*y2 - x1*z2 + y1*w2 + z1*x2,\\n" 
    h += "            w1*z2 + x1*y2 - y1*x2 + z1*w2\\n" 
    h += "        ])\\n\\n" 
    h += "// --- FIN DEL SEGMENTO ---</div></div>" 
    h += "</body></html>" 
    return render_template_string(h) 
if __name__ == '__main__': 
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 10000))) 
