import os 
from flask import Flask, render_template_string, request 
app = Flask(__name__) 
@app.route('/', methods=['GET', 'POST']) 
def home(): 
    res = None 
    idea = "" 
    if request.method == 'POST' and 'drone_idea' in request.form: 
        idea = request.form.get('drone_idea', '') 
        res = "active" 
    h = "<html><head><title>MAIA II GLI-PRO</title><style>" 
    h += "body{background:#000; color:#0ff; font-family:monospace; padding:20px;}" 
    h += ".panel{border:2px solid #0ff; padding:20px; background:#001515; margin-bottom:20px; box-shadow: 0 0 40px #0ff;}" 
    h += "details{background:#020202; border:1px solid #333; margin:8px 0; padding:12px; border-radius:5px;}" 
    h += "summary{font-weight:bold; color:yellow; cursor:pointer; padding:5px; text-transform:uppercase;}" 
    h += ".code-view{background:#000; color:#0f0; padding:20px; border-left:4px solid #f0f; white-space:pre; font-size:0.82em; line-height:1.4; font-weight:bold;}" 
    h += "input{width:55%; background:#000; color:#0ff; border:2px solid #0ff; padding:15px; font-size:1.1em;}" 
    h += "button{padding:15px 22px; font-weight:bold; cursor:pointer; margin:5px; border:none; text-transform:uppercase;}" 
    h += ".folder{margin-left:25px; border-left:1px dashed #f0f; padding-left:15px;}" 
    h += "table{width:100%; border-collapse:collapse; margin:10px 0;} td, th{padding:10px; border:1px solid #222; text-align:left;}" 
    h += "th{background:#003333; color:yellow;}" 
    h += "</style><script>" 
    h += "let v=false; function tVoz(){ let b=document.getElementById('btnVoz'); if(!v){ b.style.background='green'; v=true; " 
    h += "let m=new SpeechSynthesisUtterance('Hola Alex. Maia elevando realismo al sesenta por ciento en software y cuarenta en hardware. Arquitectura de catorce nodos activa.'); " 
    h += "m.lang='es-MX'; m.onend=()=>{ b.style.background='red'; v=false; }; window.speechSynthesis.speak(m); " 
    h += "} else { window.speechSynthesis.cancel(); b.style.background='red'; v=false; } }" 
    h += "</script></head><body>" 
    h += "<h1> [ M.A.I.A. II - SISTEMA DE ALTA INGENIERIA 60/40 ]</h1>" 
    h += "<div class='panel'><h2>ESTACION DE TRABAJO: PROYECTO TOPOGRAFICO</h2>" 
    h += "<form method='post'><input name='drone_idea' placeholder='Requerimiento tecnico...' value=''>" 
    h += "<button type='submit' style='background:#0ff; color:#000;'>GENERAR EXPEDIENTE MAESTRO</button>" 
    h += "<button type='button' style='background:#555; color:#fff;'>MEMORIA</button>" 
    h += "<button type='reset' style='background:#a00; color:#fff;'>LIMPIAR</button>" 
    h += "<button type='button' id='btnVoz' style='background:red; color:#fff;' onclick='tVoz()'>VOZ MAIA</button></form></div>" 
    if res: 
        h += "<div class='panel'><h2>EXPEDIENTE: " + idea + "</h2>" 
        h += "<details open><summary>[DIR] AGENTE SOFTWARE: PRODUCTION STACK (14 NODOS - 60% REAL)</summary><div class='folder'>" 
        h += "<details><summary>?? ai/perception</summary><div class='folder'><details><summary>?? terrain_segmentation.py</summary><div class='code-view'>import torch\\nimport numpy as np\\nclass TerrainAnalyzer:\\n    def __init__(self, weights):\\n        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\\n        self.model = torch.jit.load(weights).to(self.device).eval()\\n    @torch.no_grad()\\n    def classify(self, lidar_image):\\n        # Inferencia con precision FP16 para TensorRT\\n        input_tensor = self.preprocess(lidar_image).half()\\n        output = self.model(input_tensor.to(self.device))\\n        return self.post_process(output)</div></details></div></details>" 
        h += "<details><summary>?? fusion/ekf_core</summary><div class='folder'><details><summary>?? extended_kalman.cpp</summary><div class='code-view'>#include ^Eigen/Dense^\\nvoid EKF::update_gnss(const Vector3d& z_gps) {\\n    MatrixXd H = MatrixXd::Zero(3, 15);\\n    H.block^0, 0, 3, 3^ = Matrix3d::Identity();\\n    MatrixXd S = H * P * H.transpose() + R_gps;\\n    MatrixXd K = P * H.transpose() * S.inverse();\\n    x = x + K * (z_gps - x.head(3));\\n    P = (MatrixXd::Identity(15,15) - K * H) * P;\\n}</div></details></div></details>" 
        h += "<details><summary>?? control/low_level</summary><div class='folder'><details><summary>?? dshot_driver.c</summary><div class='code-view'>#include ^stm32h7xx_hal.h^\\nvoid send_dshot_frame(uint16_t throttle) {\\n    uint16_t packet = (throttle << 1) | (telemetry_req ? 1 : 0);\\n    uint8_t checksum = (packet ^ (packet >> 4) ^ (packet >> 8)) & 0x0F;\\n    uint16_t frame = (packet << 4) | checksum;\\n    dma_transmit_pwm_pulse(frame);\\n}</div></details></div></details>" 
        h += "<details><summary>?? navigation/astar</summary><div class='folder'><details><summary>?? voxel_planner.py</summary><div class='code-view'>import heapq\\nclass VoxelPathfinder:\\n    def compute_heuristic(self, a, b):\\n        # Distancia Manhattan 3D + Penalizacion de Altura\\n        return abs(a.x - b.x) + abs(a.y - b.y) + (abs(a.z - b.z) * 1.5)\\n    def find_path(self, octomap):\\n        while self.open_list:\\n            curr = heapq.heappop(self.open_list)[1]\\n            # Expansion de nodos en entorno denso</div></details></div></details>" 
        h += "<details><summary>?? safety/redundancy</summary><div class='folder'><details><summary>?? health_monitor.cpp</summary><div class='code-view'>void check_vitals() {\\n    if (get_esc_rpm(0) == 0) trigger_failsafe(EMERGENCY_GLIDE);\\n    if (imu_consistency_check() > 0.08f) switch_to_imu(2);\\n    if (battery_voltage() < 42.0f) start_rtl_sequence();\\n}</div></details></div></details>" 
        h += "<details><summary>?? telemetry/mavlink</summary><div class='folder'>?? high_rate_telemetry.py</div></details>" 
        h += "<details><summary>?? power/bms</summary><div class='folder'>?? can_bus_bms.py</div></details>" 
        h += "<details><summary>?? core/rtos</summary><div class='folder'>?? interrupt_handlers.c</div></details>" 
        h += "<details><summary>?? simulation/gazebo</summary><div class='folder'>?? lidar_plugin.cpp</div></details>" 
        h += "<details><summary>?? perception_lidar</summary><div class='folder'>?? point_cloud_filter.py</div></details>" 
        h += "<details><summary>?? diagnostics</summary><div class='folder'>?? bus_scanner.py</div></details>" 
        h += "<details><summary>?? mission</summary><div class='folder'>?? waypoint_manager.cpp</div></details>" 
        h += "<details><summary>?? estimation</summary><div class='folder'>?? attitude_observer.py</div></details>" 
        h += "<details><summary>?? communication/mesh</summary><div class='folder'>?? encrypted_mesh.py</div></details>" 
        h += "</div></details>" 
        h += "<details open><summary>[DIR] AGENTE HARDWARE: BOM & DOM (40% REAL)</summary><div class='folder'><table>" 
        h += "<tr><th>MODULO</th><th>ESPECIFICACION TECNICA</th><th>PROTOCOLO / POTENCIA</th></tr>" 
        h += "<tr><td><b>AVIONICA</b></td><td>Orange Cube+ (H753 dual core, 2MB Flash)</td><td>MAVLink / CAN-FD</td></tr>" 
        h += "<tr><td><b>IA EDGE</b></td><td>NVIDIA Jetson Orin Nano (40 TOPS, 8GB)</td><td>PCIe Gen3 / 15W TDP</td></tr>" 
        h += "<tr><td><b>TOPOGRAFIA</b></td><td>Lidar Livox MID-360 (Rango 250m, 360 deg)</td><td>Ethernet UDP / 6.5W</td></tr>" 
        h += "<tr><td><b>PPK/RTK</b></td><td>Emlid Reach M2 (Multi-banda, 184 canales)</td><td>UART / 5V DC</td></tr>" 
        h += "<tr><td><b>PROPULSION</b></td><td>T-Motor U8 II (KV100) + Prop 28x9.2 Carbon</td><td>DSHOT600 / 12S LiPo</td></tr>" 
        h += "<tr><td><b>ESTRUCTURA</b></td><td>Monocasco Fibra de Carbono 4K Toray + Titanio</td><td>Resistencia 120Nm/deg</td></tr>" 
        h += "</table></div></details></div>" 
    h += "<div class='panel' style='border-color:#f0f;'><h2>PROJECT LAB</h2>" 
    h += "<button>BUSCADOR</button><button style='background:#f0f;'>CREAR PROYECTO</button></div>" 
    h += "</body></html>" 
    return render_template_string(h) 
if __name__ == '__main__': 
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 10000))) 
