# -*- coding: utf-8 -*- 
import os 
from flask import Flask, render_template_string, request 
app = Flask(__name__) 
@app.route('/', methods=['GET', 'POST']) 
def home(): 
    res = None 
    idea = "" 
    if request.method == 'POST' and 'drone_idea' in request.form: 
        idea = request.form.get('drone_idea', '') 
        res = "active" 
    h = "<html><head><title>MAIA II - TOTAL STACK 60</title><style>" 
    h += "body{background:#000; color:#0ff; font-family:monospace; padding:20px;}" 
    h += ".panel{border:2px solid #0ff; padding:20px; background:#001a1a; margin-bottom:20px; box-shadow: 0 0 50px rgba(0,255,255,0.2);}" 
    h += "details{background:#050505; border:1px solid #444; margin:8px 0; padding:12px; border-radius:4px;}" 
    h += "summary{font-weight:bold; color:#ffff00; cursor:pointer; padding:5px; text-transform:uppercase; font-size:1em;}" 
    h += ".code-view{background:#000; color:#0f0; padding:15px; border-left:4px solid #f0f; white-space:pre; font-size:0.85em; height:450px; overflow-y:scroll; overflow-x:auto; line-height:1.5; border-top: 1px solid #333; margin-top:10px; display:block;}" 
    h += "input{width:50%; background:#000; color:#0ff; border:2px solid #0ff; padding:15px; font-size:1.1em;}" 
    h += "button{padding:15px 20px; font-weight:bold; cursor:pointer; margin:5px; border:none; text-transform:uppercase;}" 
    h += ".btn-gen{background:#0ff; color:#000;} .btn-mem{background:#444; color:#fff;} .btn-clear{background:#800; color:#fff;}" 
    h += ".folder{margin-left:25px; border-left:1px dotted #f0f; padding-left:15px;}" 
    h += ".hw-grid{display:grid; grid-template-columns: 1fr 1fr; gap:20px;}" 
    h += ".hw-spec{background:rgba(0,255,255,0.03); border:1px solid #0ff; padding:15px; border-radius:4px; border-left: 4px solid #f0f;}" 
    h += "table{width:100%; border-collapse:collapse; margin-top:10px;} td, th{padding:8px; border:1px solid #222; text-align:left; font-size:0.9em;}" 
    h += "th{background:#004d4d; color:#fff;}" 
    h += ".viewer-3d{width:100%; height:450px; background:#000; border:2px solid #333; display:flex; flex-direction:column; align-items:center; justify-content:center; position:relative;}" 
    h += ".drone-core{width:80px; height:25px; background:#333; border:2px solid #0ff; position:relative; animation: hover 4s infinite ease-in-out;}" 
    h += ".arm-fr{width:60px; height:6px; background:#0ff; position:absolute; top:-15px; left:60px; transform:rotate(-45deg);}" 
    h += ".arm-fl{width:60px; height:6px; background:#0ff; position:absolute; top:-15px; left:-40px; transform:rotate(45deg);}" 
    h += ".prop{width:50px; height:2px; background:#fff; position:absolute; top:-10px; animation: spin 0.1s infinite linear;}" 
    h += "@keyframes spin { from{transform:rotate(0);} to{transform:rotate(360deg);} }" 
    h += "@keyframes hover { 0%,100%{transform:translateY(0) rotate(0);} 50%{transform:translateY(-30px) rotate(2deg);} }" 
    h += "</style><script>" 
    h += "function tVoz(){ let m=new SpeechSynthesisUtterance('Alex, forzando profundidad tecnica. Desplegando stack completo de 14 nodos con logica de hardware aeroespacial. 60 por ciento confirmado.'); m.lang='es-MX'; window.speechSynthesis.speak(m); }" 
    h += "</script></head><body>" 
    h += "<h1> [ M.A.I.A. II - PRODUCTION STACK 60/60 ]</h1>" 
    h += "<div class='panel'><h2>UNIDAD DE INGENIERIA</h2>" 
    h += "<form method='post'><input name='drone_idea' placeholder='Defina mision...' value=''>" 
    h += "<button type='submit' class='btn-gen'>GENERAR EXPEDIENTE COMPLETO</button>" 
    h += "<button type='button' class='btn-mem'>MEMORIA</button>" 
    h += "<button type='reset' class='btn-clear'>LIMPIAR</button>" 
    h += "<button type='button' id='btnVoz' style='background:red; color:#fff;' onclick='tVoz()'>VOZ MAIA</button></form></div>" 
    if res: 
        h += "<div class='panel'><h2>MODELO ANALITICO 3D (ASSEMBLY)</h2><div class='viewer-3d'>" 
        h += "<div class='drone-core'><div class='arm-fr'><div class='prop'></div></div><div class='arm-fl'><div class='prop'></div></div>" 
        h += "<div class='arm-fr' style='top:35px; transform:rotate(45deg);'></div><div class='arm-fl' style='top:35px; transform:rotate(-45deg);'></div></div>" 
        h += "<p style='margin-top:80px; color:#f0f;'>[ HEXA-QUAD CONFIGURATION - TORAY M40J CHASSIS ]</p></div></div>" 
        h += "<div class='panel'><h2>EXPEDIENTE: " + idea + "</h2>" 
        h += "<details open><summary>[DIR] AGENTE SOFTWARE: PRODUCTION STACK (14 NODOS)</summary><div class='folder'>" 
        h += "<details><summary>?? control/attitude_observer.py</summary><div class='folder'><div class='code-view'>import numpy as np\\nfrom scipy.spatial.transform import Rotation\\n\\nclass AttitudeObserver:\\n    def __init__(self, dt=0.0025):\\n        self.q = np.array([1, 0, 0, 0])\\n        self.bias = np.zeros(3)\\n        self.dt = dt\\n\\n    def mahony_update(self, gyro, acc, Kp=2.0, Ki=0.005):\\n        # Normalizacion de acelerometro\\n        norm_acc = np.linalg.norm(acc)\\n        if norm_acc < 0.01: return\\n        acc /= norm_acc\\n\\n        # Direccion estimada de la gravedad\\n        v = np.array([2*(self.q[1]*self.q[3] - self.q[0]*self.q[2]),\\n                      2*(self.q[0]*self.q[1] + self.q[2]*self.q[3]),\\n                      self.q[0]**2 - self.q[1]**2 - self.q[2]**2 + self.q[3]**2])\\n\\n        # Error de correccion (Producto vectorial)\\n        error = np.cross(acc, v)\\n        self.bias += error * Ki * self.dt\\n        gyro_corr = gyro + Kp * error + self.bias\\n\\n        # Integracion de Cuaternion (Runge-Kutta 1)\\n        dq = 0.5 * self.q_mult(self.q, [0, *gyro_corr]) * self.dt\\n        self.q += dq\\n        self.q /= np.linalg.norm(self.q)</div></div></details>" 
        h += "<details><summary>?? navigation/astar_3d.cpp</summary><div class='folder'><div class='code-view'>// astar_3d.cpp - High Performance Voxel Planning\\n#include ^Eigen/Dense^\\n#include ^priority_queue^\\n\\nstruct Voxel { int x, y, z; float g_cost, h_cost; };\\n\\nfloat heuristic(Voxel a, Voxel b) {\\n    return sqrt(pow(a.x-b.x,2) + pow(a.y-b.y,2) + pow(a.z-b.z,2));\\n}\\n\\nvoid PlanPath(Octomap& map, Voxel start, Voxel goal) {\\n    // Implementacion con penalizacion por gradiente de temperatura\\n    // Prioriza voxeles con menor densidad de humo (Datos de Lidar Ouster)\\n    std::priority_queue<Voxel> open_set;\\n    start.g_cost = 0;\\n    open_set.push(start);\\n    \\n    while(!open_set.empty()) {\\n        Voxel current = open_set.top();\\n        if(current == goal) break;\\n        // ... Expansion de vecinos con chequeo de colision Octomap ...\\n    }\\n}</div></div></details>" 
        h += "<details><summary>?? telemetry/mavlink_v2.py</summary><div class='folder'>?? fast_mavlink_parser.py (CRC-16 validation)</div></details>" 
        h += "<details><summary>?? core/rtos_tasks.c</summary><div class='folder'>?? scheduler.c (400Hz Flight Control Task)</div></details>" 
        h += "<details><summary>?? power/bms_can.cpp</summary><div class='folder'>?? can_bms_driver.cpp (12S Individual Cell Monitoring)</div></details>" 
        h += "<details><summary>?? perception/lidar_ouster.py</summary><div class='folder'>?? cloud_gen.py (Point Cloud Clustering)</div></details>" 
        h += "<details><summary>?? communication/silvus_mesh.py</summary><div class='folder'>?? streamcaster_api.py (MIMO Signal Optimization)</div></details>" 
        h += "</div></details>" 
        h += "<details open><summary>[DOM] AGENTE HARDWARE: ARQUITECTURA DETALLADA</summary><div class='folder'>" 
        h += "<div class='hw-grid'>" 
        h += "<div class='hw-spec'><h3>? POTENCIA Y DISTRIBUCION</h3>" 
        h += "<b>Bateria:</b> Amprius Silicon-Anode 12S (450Wh/kg).<br>" 
        h += "<b>PDB:</b> Placa de cobre de 4 capas (4oz) con sensores Hall Allegro ACS758.<br>" 
        h += "<b>Voltaje Nominal:</b> 44.4V (Picos de 50.4V).</div>" 
        h += "<div class='hw-spec'><h3>?? PROCESAMIENTO CRITICO</h3>" 
        h += "<b>SoM:</b> Jetson Orin Nano (8GB) conectada via <b>GMSL2</b>.<br>" 
        h += "<b>FPGA:</b> Lattice CrossLink-NX para agregacion de sensores MIPI.<br>" 
        h += "<b>Bus:</b> PCIe Gen4 para SSD NVMe Industrial.</div>" 
        h += "<div class='hw-spec'><h3>?? SENSORES TACTICOS</h3>" 
        h += "<b>Termica:</b> FLIR Boson 640 (60Hz) con sincronizacion GPS PPS.<br>" 
        h += "<b>Lidar:</b> Ouster OS1-64 (V2) - 1.3M puntos/seg.<br>" 
        h += "<b>GNSS:</b> u-blox ZED-F9P (RTK con antena helicoidal).</div>" 
        h += "<div class='hw-spec'><h3>?? PROPULSION Y SIGILO</h3>" 
        h += "<b>Motores:</b> KDE 7215XF con rodamientos ceramicos hibridos.<br>" 
        h += "<b>HÇlices:</b> Owl-Design 24.5 Carbono (Serrated edge para -12dB).<br>" 
        h += "<b>ESC:</b> KDE-UAS120UVC con telemetria CAN-FD.</div>" 
        h += "</div></div></details>" 
        h += "<details open><summary>[ANX] ANALISIS DE VIABILIDAD, FISICA Y RIESGOS</summary><div class='folder'>" 
        h += "<table><tr><th>CATEGORIA</th><th>NIVEL</th><th>DETALLE TêCNICO</th><th>ACCION</th></tr>" 
        h += "<tr><td><b>VIABILIDAD</b></td><td>ALTA</td><td>Margen de potencia 2:1 con carga util de 3kg.</td><td>Validar PDB.</td></tr>" 
        h += "<tr><td><b>RIESGOS</b></td><td>CRITICO</td><td>Vibracion de alta frecuencia afectando IMU secundaria.</td><td>A§adir Alpha-Gel.</td></tr>" 
        h += "<tr><td><b>MONTAJE</b></td><td>PROC</td><td>Estructura monocasco requiere curado a 120C.</td><td>Revisar horno.</td></tr>" 
        h += "<tr><td><b>FISICA</b></td><td>CALC</td><td>Centro de presion vs Centro de gravedad (?=3.5mm).</td><td>Ajustar bateria.</td></tr>" 
        h += "<tr><td><b>COMMS</b></td><td>SEGURO</td><td>Salto de frecuencia (FHSS) activado en Silvus.</td><td>Test Jamming.</td></tr>" 
        h += "</table></div></details></div>" 
    h += "<div class='panel' style='border-color:#f0f;'><h2>PROJECT LAB</h2>" 
    h += "<button>SEARCH PROJECT</button><button style='background:#f0f;'>CREATE NEW PROJECT</button></div>" 
    h += "</body></html>" 
    return render_template_string(h) 
if __name__ == '__main__': 
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 10000))) 
